window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#f4f4f5",
        "on-surface-variant": "#a1a1aa",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004f4f",
        "on-tertiary-container": "#5a6579",
        "on-secondary-fixed": "#261a00",
        "on-primary": "#003737",
        "on-tertiary": "#263143",
        "on-tertiary-fixed": "#111c2d",
        "on-secondary": "#402d00",
        "on-secondary-container": "#6d5000",
        "on-primary-container": "#007070",
        "on-secondary-fixed-variant": "#5c4300",
        "on-primary-fixed": "#002020",
        "on-error": "#690005",
        "on-background": "#f4f4f5",
        "on-tertiary-fixed-variant": "#3c475a",
        "inverse-on-surface": "#1a1a1a",
        "inverse-surface": "#f4f4f5",
        "inverse-primary": "#006a6a",

        "surface-container-highest": "#2a2a2c",
        "surface-bright": "#3a3a3c",
        "surface-container-low": "#1a1a1c",
        "surface-container-high": "#252527",
        "surface-container": "#1f1f21",
        "surface-container-lowest": "#0a0a0b",
        "surface-variant": "#2a2a2c",
        "surface-dim": "#121214",
        "surface-tint": "#00dddd",
        surface: "#121214",

        tertiary: "#ffffff",
        "secondary-fixed": "#ffdfa0",
        "primary-fixed": "#00fbfb",
        "primary-fixed-dim": "#00dddd",
        "secondary-fixed-dim": "#fbbc00",
        "tertiary-fixed": "#d8e3fb",
        "tertiary-fixed-dim": "#bcc7de",

        primary: "#ffffff",
        secondary: "#ffe2ab",
        background: "#0f0f11",
        "primary-container": "#00fbfb",
        "secondary-container": "#ffbf00",
        "tertiary-container": "#d8e3fb",

        outline: "#71717a",
        "outline-variant": "#3f3f46",
        error: "#ff8a82",
        "error-container": "#931a1f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "panel-gap": "16px",
        unit: "8px",
        "margin-edge": "32px",
        "container-max": "1280px",
        gutter: "24px",
      },
      fontFamily: {
        h2: ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        h1: ["Inter", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        h2: ["28px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["17px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.12em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "1.55", fontWeight: "400" }],
        h1: ["44px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" }],
      },
    },
  },
};
